export interface ClienteInterface{
    IDCliente?:string;
    Nombre?:string;
    RFC?:string;
    Usuario?:string;
    Pais?:string;
    Municipio?:string;
    Direccion?:string;
    Puesto?:string;
    Tel?:string;
    NombreComercial?:string;
    EEstado?:string;
    Correo?:string;
    Actipass?:string;
    IDConfig?:string;
    Estado?:string;
    TPersona?:string;
    Apellidos?:string;
    IDEmpresa?:string;
    Telcontact?:string;
}