import { NgModule } from '@angular/core';
import {DragDropModule} from '@angular/cdk/drag-drop';

import {
    MatButtonModule,
    MatCheckboxModule,
    MatDialogModule,
    MatCardModule,
    MatToolbarModule,
    MatIconModule,
    MatButtonToggleModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatSortModule,
    MatTableModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatMenuModule,
    MatTooltipModule,
    MatDividerModule,
    MatListModule,
    MatRadioModule,
    MatStepperModule,
    MatSliderModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule
} from '@angular/material';
@NgModule({
    imports: [
        MatButtonModule,
        MatCheckboxModule,
        MatDialogModule,
        MatCardModule,
        MatIconModule,
        MatToolbarModule,
        DragDropModule,
        MatButtonToggleModule,
        MatExpansionModule,
        MatPaginatorModule,
        MatSortModule,
        MatTableModule,
        MatFormFieldModule,
        MatInputModule,
        MatSelectModule,
        MatMenuModule,
        MatTooltipModule,
        MatDividerModule,
        MatListModule,
        MatRadioModule,
        MatStepperModule,
        MatSliderModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatMenuModule,
        MatSlideToggleModule
    ],
    providers: [
        MatDatepickerModule,
      ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatDialogModule,
        MatCardModule,
        MatIconModule,
        MatToolbarModule,
        DragDropModule,
        MatButtonToggleModule,
        MatExpansionModule,
        MatPaginatorModule,
        MatSortModule,
        MatTableModule,
        MatFormFieldModule,
        MatInputModule,
        MatSelectModule,
        MatMenuModule,
        MatTooltipModule,
        MatDividerModule,
        MatListModule,
        MatRadioModule,
        MatStepperModule,
        MatSliderModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatMenuModule,
        MatSlideToggleModule
    ]

})
export class MaterialModule{}